USE [master]
GO
/****** Object:  Database [BOOK_DB]    Script Date: 10/22/2021 4:50:29 PM ******/
CREATE DATABASE [BOOK_DB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BOOK_DB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\BOOK_DB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BOOK_DB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\BOOK_DB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [BOOK_DB] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BOOK_DB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [BOOK_DB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [BOOK_DB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [BOOK_DB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [BOOK_DB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [BOOK_DB] SET ARITHABORT OFF 
GO
ALTER DATABASE [BOOK_DB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [BOOK_DB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [BOOK_DB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [BOOK_DB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [BOOK_DB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [BOOK_DB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [BOOK_DB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [BOOK_DB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [BOOK_DB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [BOOK_DB] SET  ENABLE_BROKER 
GO
ALTER DATABASE [BOOK_DB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [BOOK_DB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [BOOK_DB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [BOOK_DB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [BOOK_DB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [BOOK_DB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [BOOK_DB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [BOOK_DB] SET RECOVERY FULL 
GO
ALTER DATABASE [BOOK_DB] SET  MULTI_USER 
GO
ALTER DATABASE [BOOK_DB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [BOOK_DB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [BOOK_DB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [BOOK_DB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [BOOK_DB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [BOOK_DB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [BOOK_DB] SET QUERY_STORE = OFF
GO
USE [BOOK_DB]
GO
/****** Object:  Table [dbo].[Book]    Script Date: 10/22/2021 4:50:30 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Book](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Title] [nvarchar](max) NULL,
	[Author] [nvarchar](255) NULL,
	[PublicationDate] [varchar](50) NULL,
	[ISBN] [bigint] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  StoredProcedure [dbo].[SP_ADD_BOOK]    Script Date: 10/22/2021 4:50:30 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[SP_ADD_BOOK](@TITLE nvarchar(MAX) ='', @AUTHOR nvarchar(255)='', @PublicationDate VARCHAR(50),  @ISBN BIGINT =0,  @ID  INT =0 OUTPUT)
AS 
BEGIN
	INSERT INTO BOOK (TITLE, AUTHOR, PublicationDate, ISBN) VALUES (@TITLE, @AUTHOR, @PublicationDate, @ISBN);

	SET @ID=SCOPE_IDENTITY()
				  RETURN @ID
END
GO
/****** Object:  StoredProcedure [dbo].[SP_DELETE_BOOK]    Script Date: 10/22/2021 4:50:30 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[SP_DELETE_BOOK](@ID INT)
AS 
BEGIN
	DELETE FROM BOOK WHERE ID = @ID;
END
GO
/****** Object:  StoredProcedure [dbo].[SP_GET_BOOK]    Script Date: 10/22/2021 4:50:30 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[SP_GET_BOOK](@TITLE nvarchar(MAX) ='', @AUTHOR nvarchar(255)='', @ISBN BIGINT =0)
AS 
BEGIN
	SELECT * FROM BOOK WHERE TITLE = @TITLE OR AUTHOR =@AUTHOR OR ISBN =@ISBN;
END
GO
/****** Object:  StoredProcedure [dbo].[SP_UPDATE_BOOK]    Script Date: 10/22/2021 4:50:30 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[SP_UPDATE_BOOK](@ID INT, @TITLE nvarchar(MAX) ='', @AUTHOR nvarchar(255)='',  @ISBN BIGINT =0)
AS 
BEGIN
	UPDATE BOOK SET TITLE = @TITLE, AUTHOR = @AUTHOR, ISBN = @ISBN WHERE ID = @ID;

	SET @ID=SCOPE_IDENTITY()
				  RETURN @ID
END
GO
USE [master]
GO
ALTER DATABASE [BOOK_DB] SET  READ_WRITE 
GO
